name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/working-cicd:v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/working-cicd:v1
    - name: pulling the image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/working-cicd:v1
    - name: running the container
      run: docker run --name test -p 80:80 -d ${{ secrets.DOCKER_USERNAME }}/working-cicd:v1
    - name: ngrok
      run: curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
           sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
           echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
           sudo tee /etc/apt/sources.list.d/ngrok.list && \
           sudo apt update && sudo apt install ngrok
    - name: connectnig account 
      run: ngrok config add-authtoken 2MznvSeI4IPtagqiIKAC8egwXn8_7HX16rTuTMGubSzbSzJL3
    - name: starting the tunnel
      run: ngrok http 80
      

 
