name: Docker Image CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file fe/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/frontend:v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:v1
    - name: pulling the image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:v1
    - name: running the container
      run: docker run --name test -p 80:80 -d ${{ secrets.DOCKER_USERNAME }}/frontend:v1
    - name: ngrok downloading
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
    - name: unzibing the zip folder
      run: sudo tar -xvzf ngrok-v3-stable-linux-amd64.tgz
    - name: connectnig account 
      run: ./ngrok config add-authtoken ${{ secrets.TOKEN }}   
    - name: moving the file
      run:  mv ngrok /usr/local/bin
    - name: starting the tunnel
      run:  ngrok http 80
---
name: Docker Image CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file be/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/backend:v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:v1
    - name: pulling the image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/backend:v1
    - name: running the container
      run: docker run --name test -p 80:80 -d ${{ secrets.DOCKER_USERNAME }}/backend:v1
    - name: ngrok downloading
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
    - name: unzibing the zip folder
      run: sudo tar -xvzf ngrok-v3-stable-linux-amd64.tgz
    - name: connectnig account 
      run: ./ngrok config add-authtoken ${{ secrets.TOKEN }}   
    - name: moving the file
      run:  mv ngrok /usr/local/bin
    - name: starting the tunnel
      run:  ngrok http 80
